name: Test
run-name: Test
on: [push]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: linux command
              run: | 
                mkdir test dir
                cd test
                touch test.py
                sudo apt-get install python3 python-is-python3
                echo "print(\"Hello World!\")" >> test.py
                
                python3 test.py
                echo "Done"

